//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armes
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public double Pickrate { get; set; }
        public int Ammo { get; set; }
        public int Magazine { get; set; }
    }
}
