//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueurs
    {
        public int SteamId { get; set; }
        public string Username { get; set; }
        public string PeakRank { get; set; }
        public System.TimeSpan Hours { get; set; }
        public int Level { get; set; }
        public double KDA { get; set; }
        public int NbPlayedGames { get; set; }
    
        public virtual Stats Stats { get; set; }
        public virtual StatsTwentyDays StatsTwentyDays { get; set; }
    }
}
