//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public int SteamId { get; set; }
        public int Ranknumber { get; set; }
        public int Win { get; set; }
        public int Loss { get; set; }
        public double Winrate { get; set; }
    }
}
