//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public string Name { get; set; }
        public double WinrateCT { get; set; }
        public double WinrateT { get; set; }
        public double Banrate { get; set; }
    
        public virtual Rotation Rotation { get; set; }
    }
}
