//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsTwentyDays
    {
        public int Id_Joueurs { get; set; }
        public double Looserate { get; set; }
        public double Winrate { get; set; }
        public double HSrate { get; set; }
        public double Avghit { get; set; }
        public int GameNumber { get; set; }
        public string Rank { get; set; }
    
        public virtual Joueurs Joueurs { get; set; }
    }
}
